# Generated by Django 2.1.15 on 2022-05-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajachicaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigocajachica',
            fields=[
                ('codcajachica', models.IntegerField(db_column='CodCajaChica', primary_key=True, serialize=False)),
                ('concepto', models.CharField(blank=True, db_column='Concepto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CodigoCajaChica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigoFactura',
            fields=[
                ('tipo', models.IntegerField(db_column='Tipo', primary_key=True, serialize=False)),
                ('factura', models.CharField(blank=True, db_column='Factura', max_length=50, null=True)),
                ('codcomprobante', models.CharField(blank=True, db_column='CodComprobante', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Codigo Factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condicioniva',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('condicioniva', models.CharField(db_column='CondicionIVA', max_length=50)),
            ],
            options={
                'db_table': 'CondicionIVA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentasContables',
            fields=[
                ('n·mero_de_cuenta', models.FloatField(db_column='N·mero de Cuenta', primary_key=True, serialize=False)),
                ('ctapresu', models.IntegerField(blank=True, db_column='CtaPresu', null=True)),
                ('descripción', models.CharField(blank=True, db_column='Descripci¾n', max_length=70, null=True)),
                ('dpto', models.SmallIntegerField(blank=True, db_column='Dpto', null=True)),
                ('n·mero', models.SmallIntegerField(blank=True, db_column='N·mero', null=True)),
                ('nivel2', models.CharField(blank=True, db_column='Nivel2', max_length=50, null=True)),
                ('suma', models.CharField(blank=True, db_column='Suma', max_length=50, null=True)),
                ('descripcionsuma', models.CharField(blank=True, db_column='DescripcionSuma', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cuentas Contables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentasPresupuestaria',
            fields=[
                ('ctapresu', models.CharField(db_column='CtaPresu', max_length=50, primary_key=True, serialize=False)),
                ('descripcionctapresu', models.CharField(blank=True, db_column='DescripcionCtaPresu', max_length=50, null=True)),
                ('subcuenta', models.FloatField(db_column='SubCuenta')),
                ('descripcion_subcuenta', models.CharField(blank=True, db_column='Descripcion Subcuenta', max_length=70, null=True)),
                ('cuenta', models.FloatField(blank=True, db_column='Cuenta', null=True)),
                ('descripcion_cuenta', models.CharField(blank=True, db_column='Descripcion Cuenta', max_length=70, null=True)),
            ],
            options={
                'db_table': 'Cuentas Presupuestaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErogacionesPresupuestarias',
            fields=[
                ('coddpto', models.IntegerField(db_column='CodDpto', primary_key=True, serialize=False)),
                ('cuenta', models.CharField(blank=True, db_column='Cuenta', max_length=7, null=True)),
                ('departamento', models.CharField(blank=True, db_column='Departamento', max_length=50, null=True)),
                ('suma', models.CharField(blank=True, db_column='Suma', max_length=7, null=True)),
                ('cuentaiva', models.CharField(blank=True, db_column='CuentaIva', max_length=8, null=True)),
                ('subcentaiva', models.CharField(blank=True, db_column='SubCentaIva', max_length=255, null=True)),
                ('ctapercib', models.CharField(blank=True, db_column='CtaPercIB', max_length=255, null=True)),
                ('tem', models.CharField(blank=True, db_column='TEM', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Erogaciones Presupuestarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estadoid', models.AutoField(db_column='EstadoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Excepciones',
            fields=[
                ('excepcionid', models.AutoField(db_column='ExcepcionID', primary_key=True, serialize=False)),
                ('sectorid', models.IntegerField(db_column='SectorID')),
                ('creado', models.DateField(db_column='Creado')),
                ('modificado', models.DateField(db_column='Modificado')),
                ('usuarioid', models.IntegerField(db_column='UsuarioID')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Excepciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fechacierre',
            fields=[
                ('idfechacierre', models.AutoField(db_column='idFechaCierre', primary_key=True, serialize=False)),
                ('fechacierre', models.DateField(db_column='FechaCierre')),
            ],
            options={
                'db_table': 'FechaCierre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilitocajachica',
            fields=[
                ('codsector', models.IntegerField(db_column='CodSector', primary_key=True, serialize=False)),
                ('fechacajachica', models.DateTimeField(db_column='FechaCajaChica')),
                ('montoasignado', models.DecimalField(blank=True, db_column='MontoAsignado', decimal_places=4, max_digits=19, null=True)),
                ('rendido', models.DecimalField(blank=True, db_column='Rendido', decimal_places=4, max_digits=19, null=True)),
                ('encaja', models.DecimalField(blank=True, db_column='EnCaja', decimal_places=4, max_digits=19, null=True)),
                ('estadoid', models.IntegerField(blank=True, db_column='EstadoID', null=True)),
                ('usuariocambioestado', models.IntegerField(blank=True, db_column='UsuarioCambioEstado', null=True)),
                ('fechacambioestado', models.DateTimeField(blank=True, db_column='FechaCambioEstado', null=True)),
            ],
            options={
                'db_table': 'HabilitoCajaChica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('n·mero_de_cuenta', models.FloatField(db_column='N·mero de Cuenta', primary_key=True, serialize=False)),
                ('código_de_integración', models.CharField(blank=True, db_column='C¾digo de Integraci¾n', max_length=50, null=True)),
                ('cuenta_en_que_suma', models.FloatField(blank=True, db_column='Cuenta en que suma', null=True)),
                ('number_1', models.FloatField(blank=True, db_column='1', null=True)),
                ('number_2', models.FloatField(blank=True, db_column='2', null=True)),
                ('number_3', models.FloatField(blank=True, db_column='3', null=True)),
                ('number_4', models.FloatField(blank=True, db_column='4', null=True)),
                ('number_5', models.FloatField(blank=True, db_column='5', null=True)),
                ('crÚdito', models.FloatField(blank=True, db_column='CrÚdito', null=True)),
                ('descripción', models.CharField(blank=True, db_column='Descripci¾n', max_length=70, null=True)),
                ('total_comprometido', models.FloatField(blank=True, db_column='Total Comprometido', null=True)),
                ('total_crÚdito', models.FloatField(blank=True, db_column='Total CrÚdito', null=True)),
                ('cuenta_contable', models.FloatField(blank=True, db_column='Cuenta Contable', null=True)),
                ('n·mero', models.SmallIntegerField(blank=True, db_column='N·mero', null=True)),
                ('balance', models.SmallIntegerField(blank=True, db_column='BALANCE', null=True)),
                ('pp', models.CharField(blank=True, db_column='PP', max_length=10, null=True)),
                ('control', models.BooleanField(blank=True, db_column='Control', null=True)),
            ],
            options={
                'db_table': 'Maestro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('idmovimiento', models.AutoField(db_column='IdMovimiento', primary_key=True, serialize=False)),
                ('codsector', models.IntegerField(blank=True, db_column='CodSector', null=True)),
                ('coddpto', models.IntegerField(blank=True, db_column='CodDpto', null=True)),
                ('fechagrabacion', models.DateTimeField(blank=True, db_column='FechaGrabacion', null=True)),
                ('fechacajachica', models.DateTimeField(blank=True, db_column='FechaCajaChica', null=True)),
                ('codproveedor', models.IntegerField(blank=True, db_column='CodProveedor', null=True)),
                ('proveedor', models.CharField(blank=True, db_column='Proveedor', max_length=50, null=True)),
                ('cuit', models.CharField(blank=True, db_column='CUIT', max_length=13, null=True)),
                ('tipofactura', models.IntegerField(blank=True, db_column='TipoFactura', null=True)),
                ('nrofactura', models.CharField(blank=True, db_column='NroFactura', max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('articulo', models.CharField(blank=True, db_column='Articulo', max_length=50, null=True)),
                ('neto', models.DecimalField(blank=True, db_column='Neto', decimal_places=4, max_digits=19, null=True)),
                ('netonogravado', models.DecimalField(blank=True, db_column='NetoNoGravado', decimal_places=4, max_digits=19, null=True)),
                ('neto21', models.DecimalField(blank=True, db_column='Neto21', decimal_places=4, max_digits=19, null=True)),
                ('iva21', models.DecimalField(blank=True, db_column='Iva21', decimal_places=4, max_digits=19, null=True)),
                ('neto105', models.DecimalField(blank=True, db_column='Neto105', decimal_places=4, max_digits=19, null=True)),
                ('iva105', models.DecimalField(blank=True, db_column='Iva105', decimal_places=4, max_digits=19, null=True)),
                ('iva', models.DecimalField(blank=True, db_column='IVA', decimal_places=4, max_digits=19, null=True)),
                ('percib', models.DecimalField(blank=True, db_column='PercIB', decimal_places=4, max_digits=19, null=True)),
                ('tem', models.DecimalField(blank=True, db_column='TEM', decimal_places=4, max_digits=19, null=True)),
                ('percepcioniva', models.DecimalField(blank=True, db_column='PercepcionIVA', decimal_places=4, max_digits=19, null=True)),
                ('otrostrib', models.DecimalField(blank=True, db_column='OtrosTrib', decimal_places=4, max_digits=19, null=True)),
                ('ajusteredondeo', models.DecimalField(blank=True, db_column='AjusteRedondeo', decimal_places=4, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=4, max_digits=19, null=True)),
                ('cuentacontable', models.FloatField(blank=True, db_column='CuentaContable', null=True)),
                ('cuentapresupuestaria', models.IntegerField(blank=True, db_column='CuentaPresupuestaria', null=True)),
                ('subcuenta', models.IntegerField(blank=True, db_column='SubCuenta', null=True)),
                ('idautorizado', models.IntegerField(blank=True, db_column='IdAutorizado', null=True)),
                ('exento', models.BooleanField(blank=True, db_column='Exento', null=True)),
                ('estadoid', models.IntegerField(blank=True, db_column='EstadoID', null=True)),
                ('usuariocambioestado', models.IntegerField(blank=True, db_column='UsuarioCambioEstado', null=True)),
                ('fechacambioestado', models.DateTimeField(blank=True, db_column='FechaCambioEstado', null=True)),
            ],
            options={
                'db_table': 'Movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientosproveedores',
            fields=[
                ('idmovimiento', models.AutoField(db_column='IdMovimiento', primary_key=True, serialize=False)),
                ('codsector', models.SmallIntegerField(blank=True, db_column='CodSector', null=True)),
                ('nro_cuenta', models.FloatField(blank=True, db_column='Nro cuenta', null=True)),
                ('codcajachica', models.IntegerField(blank=True, db_column='CodCajaChica', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('importe', models.DecimalField(blank=True, db_column='Importe', decimal_places=4, max_digits=19, null=True)),
                ('asiento', models.IntegerField(blank=True, db_column='Asiento', null=True)),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=255, null=True)),
                ('anulado', models.BooleanField(blank=True, db_column='Anulado', null=True)),
                ('fechaanulacion', models.DateTimeField(blank=True, db_column='FechaAnulacion', null=True)),
                ('idusuario', models.IntegerField(blank=True, db_column='IdUsuario', null=True)),
                ('fechacajachica', models.DateTimeField(blank=True, db_column='FechaCajaChica', null=True)),
            ],
            options={
                'db_table': 'MovimientosProveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cuit', models.CharField(db_column='CUIT', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, db_column='Provincia', max_length=30, null=True)),
                ('codpostal', models.IntegerField(blank=True, db_column='CodPostal', null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('condicioniva', models.IntegerField(blank=True, db_column='CondicionIVA', null=True)),
                ('alta', models.DateTimeField(blank=True, db_column='Alta', null=True)),
                ('modificacion', models.DateTimeField(blank=True, db_column='Modificacion', null=True)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('codsector', models.SmallIntegerField(db_column='CodSector', primary_key=True, serialize=False)),
                ('sectorcontable', models.CharField(blank=True, db_column='SectorContable', max_length=50, null=True)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=50, null=True)),
                ('erogacion', models.IntegerField(blank=True, db_column='Erogacion', null=True)),
                ('cuentaiva', models.CharField(blank=True, db_column='CuentaIVA', max_length=50, null=True)),
                ('subcuentaiva', models.CharField(blank=True, db_column='SubCuentaIVa', max_length=50, null=True)),
                ('ctapercib', models.CharField(blank=True, db_column='CtaPercIB', max_length=255, null=True)),
                ('tem', models.CharField(blank=True, db_column='TEM', max_length=255, null=True)),
                ('contraseña', models.CharField(blank=True, db_column='Contrase±a', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('montoautorizado', models.DecimalField(blank=True, db_column='MontoAutorizado', decimal_places=4, max_digits=19, null=True)),
                ('idautorizado', models.IntegerField(blank=True, db_column='IdAutorizado', null=True)),
                ('tipodepartamento', models.IntegerField(blank=True, db_column='TipoDepartamento', null=True)),
                ('cuentanombre', models.CharField(blank=True, db_column='CuentaNombre', max_length=255, null=True)),
                ('essucursal', models.BooleanField(blank=True, db_column='EsSucursal', null=True)),
            ],
            options={
                'db_table': 'Sectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdepartamentos',
            fields=[
                ('tipodepartamentoid', models.AutoField(db_column='TipoDepartamentoId', primary_key=True, serialize=False)),
                ('descripciontipodepartamento', models.CharField(blank=True, db_column='DescripcionTipoDepartamento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TiposDepartamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioid', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('usuariolegajo', models.IntegerField(blank=True, db_column='UsuarioLegajo', null=True)),
                ('usuariodescripcion', models.CharField(blank=True, db_column='UsuarioDescripcion', max_length=255, null=True)),
                ('usuariocontraseña', models.CharField(blank=True, db_column='UsuarioContrase±a', max_length=255, null=True)),
                ('usuarioestado', models.CharField(blank=True, db_column='UsuarioEstado', max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariosautorizados',
            fields=[
                ('idautorizado', models.AutoField(db_column='IdAutorizado', primary_key=True, serialize=False)),
                ('codsector', models.IntegerField(blank=True, db_column='CodSector', null=True)),
                ('legajo', models.IntegerField(blank=True, db_column='Legajo', null=True)),
                ('usuarioautorizado', models.CharField(blank=True, db_column='UsuarioAutorizado', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('fechaalta', models.DateTimeField(blank=True, db_column='FechaAlta', null=True)),
            ],
            options={
                'db_table': 'UsuariosAutorizados',
                'managed': False,
            },
        ),
    ]
